# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18UJlauICdCz6kHJEcIFnCrsE4GIa3RXH
"""

from google.colab import drive
drive.mount('/content/drive')

# import os

# # Path to the subfolder
# subfolder_path = "/content/drive/My Drive/image_captioning/Images"

# # List all files in the subfolder
# files = [f for f in os.listdir(subfolder_path) if os.path.isfile(os.path.join(subfolder_path, f))]

# # Count the number of files
# num_files = len(files)

# print(f"Number of files in '{subfolder_path}': {num_files}")

file_path = "/content/drive/My Drive/image_captioning"

import os

folder_path = "/content/drive/My Drive/image_captioning"  # Replace with the actual path to your folder
os.chdir(folder_path)

# Confirm the current working directory
print("Current Working Directory:", os.getcwd())

files = os.listdir()  # Lists all files in the current working directory
print("Files in xyz folder:", files)

import cv2
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import regex as re
import json
import collections
from keras.models import Model, load_model
from keras.preprocessing import image
from keras.applications.resnet50 import ResNet50, preprocess_input, decode_predictions
from keras.preprocessing.sequence import pad_sequences
from keras.layers import *
from keras.applications.vgg16 import VGG16
import pickle
from keras.utils import to_categorical
from keras.optimizers import Adam
import random
from PIL import Image

#Read Text Captions
def readTextFile(path):
    with open(path) as f:
        captions = f.read()
    return captions

captions = readTextFile('Flickr_TextData/Flickr8k.token.txt')
captions = captions.split('\n')[:-1]
captions[0].split('\t')[0].split('.')[0]

#Clean Text
def cleanText(sentence):
    sentence = sentence.lower()
    sentence = re.sub('[^a-z]+', ' ', sentence)
    sentence = sentence.split()

    sentence = [s for s in sentence if len(s)>1]
    sentence = ' '.join(sentence)
    return sentence

#Dictionary to map image to list of captions
descriptions = {}
for x in captions:
    first, second = x.split('\t')
    img_name = first.split('.')[0]

    #create img_id if not present
    if descriptions.get(img_name) is None:
        descriptions[img_name] = []
    descriptions[img_name].append(cleanText(second))

descriptions['1000268201_693b08cb0e']

IMG_PATH = 'Images/'
path = IMG_PATH+'1000268201_693b08cb0e.jpg'
img = cv2.imread(path)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
plt.imshow(img)
print(path)

#Write data into new file
with open('descriptions.txt', 'w') as f:
    f.write(str(descriptions))

descriptions = None
with open('descriptions.txt', 'r', encoding='utf8') as f:
    descriptions = f.read()
json_string = descriptions.replace("'", "\"")
descriptions = json.loads(json_string)

print(type(descriptions))

#Vocab
vocab = set()
for key in descriptions.keys():
    for sentence in descriptions[key]:
        vocab.update(sentence.split())

#Total words across the file
total_words = []
for key in descriptions.keys():
    [total_words.append(i) for des in descriptions[key] for i in des.split()]

#Filter words a/c to freq
THRESHOLD = 10
counter = collections.Counter(total_words)
freq_cnt = dict(counter)
sorted_freq_cnt = sorted(freq_cnt.items(), reverse=True, key = lambda x:x[1])
sorted_freq_cnt = [x for x in sorted_freq_cnt if int(x[1])>THRESHOLD]
total_words = [x[0] for x in sorted_freq_cnt]

len(total_words)

#Training Data
train_file_data = readTextFile('Flickr_TextData/Flickr_8k.trainImages.txt')
test_file_data = readTextFile('Flickr_TextData/Flickr_8k.testImages.txt')

train = train_file_data.split('\n')[:-1]
train = [row.split('.')[0] for row in train_file_data.split('\n')[:-1]]
test = [row.split('.')[0] for row in test_file_data.split('\n')[:-1]]

train_descriptions = {}
for img_id in train:
    train_descriptions[img_id] = []
    for caption in descriptions[img_id]:
        cap_to_append = "<s> " + caption + " <e>"
        train_descriptions[img_id].append(cap_to_append)

#Image Feature Extraction
model = ResNet50(weights='imagenet', input_shape=(224,224,3))
model.summary()

model_new = Model(model.input, model.layers[-2].output)

def preprocess_img(img):
    img = image.load_img(img, target_size=(224,224))
    img = image.img_to_array(img)
    img = np.expand_dims(img, axis = 0)
    #Normalisation
    img = preprocess_input(img)
    return img

def encode_img(img):
    img = preprocess_img(img)
    feature_vector = model_new.predict(img)
    # print(feature_vector.shape)
    feature_vector = feature_vector.reshape((-1,))
    # print(feature_vector.shape)
    return feature_vector

# encoding_train = {}
# #image_id --> feature vector
# for ix, img_id in enumerate(train):
#     img_path = IMG_PATH+'/'+img_id+".jpg"
#     encoding_train[img_id] = encode_img(img_path)
#     if ix%500 ==0:
#         print(f"Step no {ix}")

# #Store encodings in file
# with open ('encoded_train_features.pkl', 'wb') as f:
#     pickle.dump(encoding_train, f)

# encoding_test = {}
# for ix, img_id in enumerate(test):
#     img_path = IMG_PATH+'/'+img_id+".jpg"
#     encoding_test[img_id] = encode_img(img_path)
#     if ix%200 ==0:
#         print(f"Step no {ix}")
# #Store encodings in file
# with open ('encoded_test_features.pkl', 'wb') as f:
#     pickle.dump(encoding_test, f)

with open('encoded_train_features.pkl', 'rb') as f:
    encoding_train = pickle.load(f)
with open('encoded_test_features.pkl', 'rb') as f:
    encoding_test = pickle.load(f)

#Data pre for captions
word2idx = {}
idx2word = {}
for i,word in enumerate(total_words):
    word2idx[word] = i+1 #reserve zero for sentence ends
    idx2word[i+1] = word
vocab_size = len(idx2word)
idx2word[vocab_size+1] = '<s>'
word2idx['<s>'] = vocab_size+1
idx2word[vocab_size+2] = '<e>'
word2idx['<e>'] = vocab_size+2
vocab_size = len(idx2word) #0 for sentence ends
vocab_size += 1

max_len = 0
for key in train_descriptions.keys():
    for cap in train_descriptions[key]:
        max_len = max(max_len, len(cap.split()))
print(max_len)

"""## Data Generator"""

# def data_generator(train_descriptions, encoding_train, word_to_idx, max_len, batch_size):
#     X1,X2,y = [],[],[]
#     n = 0
#     while True:
#         for key,desc_list in train_descriptions.items():
#             photo = encoding_train[key]
#             #Python practice/image_captioning/Images/1000268201_693b08cb0e.jpg
#             for cap in desc_list:
#                 seq = [word_to_idx[word]  for word in cap.split() if word in word_to_idx]
#                 for i in range(1,len(seq)):
#                     xi = seq[:i]
#                     yi = seq[i]
#                     #0 is padding word
#                     xi = pad_sequences([xi], maxlen= max_len, value=0, padding='post')[0]
#                     yi = to_categorical(yi, num_classes=vocab_size)

#                     X1.append(photo)
#                     X2.append(xi)
#                     y.append(yi)
#                     n += 1
#                 if n == batch_size:
#                     print("Example target (y):", np.array(y))
#                     yield ((np.array(X1), np.array(X2)), np.array(y))
#                     X1, X2, y =[],[],[]
#                     n=0

def data_generator(train_descriptions, encoding_train, word_to_idx, max_len, batch_size):
    while True:
        X1, X2, y = [], [], []
        for _ in range(batch_size):
            # Randomly select an image key
            key = random.choice(list(train_descriptions.keys()))
            photo = encoding_train[key]

            # Select a random caption for the chosen image
            desc_list = train_descriptions[key]
            caption = random.choice(desc_list)

            seq = [word_to_idx[word] for word in caption.split() if word in word_to_idx]
            for i in range(1, len(seq)):
                xi = seq[:i]
                xi = pad_sequences([xi], maxlen=max_len, value=0, padding='post')[0]
                yi = to_categorical(seq[i], num_classes=vocab_size)

                X1.append(photo)
                X2.append(xi)
                y.append(yi)

        yield ((np.array(X1), np.array(X2)), np.array(y))
        X1, X2, y = [], [], []  # Clear lists after each batch

"""## Word Embeddings"""

embeddings_index = {}
with open('glove.6B.50d.txt', encoding='utf8') as f:
    for line in f:
        values = line.split()
        word = values[0]
        embedding = np.array(values[1:], dtype = 'float')
        embeddings_index[word] = embedding

emb_dim = 50
def get_embedding_matrix(emb_idx):
    matrix = np.zeros((vocab_size, emb_dim))
    for word,idx in word2idx.items():
        embedding_vector = emb_idx.get(word)
        if embedding_vector is not None:
            matrix[idx] = embedding_vector
    return matrix
embedding_matrix = get_embedding_matrix(embeddings_index)

"""## Model Architecture"""

#image feature extractor model
inputs1 = Input(shape=(2048,))
fe1 = Dropout(0.5)(inputs1)
fe2 = Dense(256, activation='relu')(fe1)

#partial caption sequence model
inputs2 = Input(shape = (max_len,))
se1 = Embedding(vocab_size, emb_dim, mask_zero=True)(inputs2)
se2 = Dropout(0.5)(se1)
se3 = LSTM(256)(se2)

#decoder feed forward model
decoder1 = add([fe2,se3])
decoder2 = Dense(256, activation='relu')(decoder1)
outputs = Dense(vocab_size, activation='softmax')(decoder2)

#merge the input models
model = Model(inputs = [inputs1, inputs2], outputs = outputs)
model.summary()

model.layers[2].set_weights([embedding_matrix])
model.layers[2].trainable = False

adam = Adam()

model.compile(loss = 'categorical_crossentropy', optimizer = adam)

"""## Model Training"""

epochs = 30
batch_size = 3
steps = len(train_descriptions)//batch_size

def train_model(epochs, model):
    for i in range(epochs):
        print(f"Epoch:- {i}")
        generator = data_generator(train_descriptions, encoding_train, word2idx, max_len, batch_size)
        model.fit(generator, epochs = 1, steps_per_epoch = steps, verbose = 1)
        model.save_weights(f'./saved_models/model_{i}.weights.h5')  # Updated file extension



train_model(epochs, model)

load_model = model.load_weights('./saved_models/model_17.weights.h5')

model.save('./saved_models/full_model.keras')

model = load_model('./saved_models/full_model.keras')

def predict_caption(photo):
  in_text = "<s>"
  for i in range(max_len):
    sequence = [word2idx[w] for w in in_text.split() if w in word2idx]
    sequence = pad_sequences([sequence], maxlen=max_len, padding='post')

    ypred = model.predict([photo,sequence])
    ypred = ypred.argmax() #Word with max prob(Greedy Sampling)///mean search
    word = idx2word[ypred]
    in_text += (' ' + word)

    if word == '<e>':
      break
  final_caption = in_text.split()[1:-1]
  final_caption = ' '.join(final_caption)
  return final_caption

#Pick random images and check
for i in range(15):
  no = np.random.randint(0,1000)
  img_name = list(encoding_test.keys())[no]
  photo_2048 = encoding_test[img_name].reshape((1,2048))

  i = plt.imread('Images'+'/'+img_name+'.jpg')
  caption = predict_caption(photo_2048)
  print(caption)
  plt.imshow(i)
  plt.axis('off')
  plt.show()

def generate_caption_from_image(image_path):

    # Preprocess the image
    img = preprocess_img(image_path)

    # Extract features using the ResNet50 model
    photo_features = model_new.predict(img).reshape((1, 2048))

    # Generate the caption
    caption = predict_caption(photo_features)
    img = Image.open(image_path)  # Load the image using PIL
    plt.imshow(img)  # Display the image
    plt.axis('off')  # Hide axis
    plt.show()
    return caption

# Test the new function with a sample image
image_path = "./kanyinion.jpeg"  # Replace with your image file path
caption = generate_caption_from_image(image_path)
print(f"Caption for the image: {caption}")

caption = generate_caption_from_image("./muffoo.jpeg")
print(caption)

caption = generate_caption_from_image("./kanyinion.jpeg")
print(caption)

